/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Point } from "./models/graph.model";
export namespace Components {
    interface MyGraph {
        "name": string;
        "points": Point[];
    }
    interface MyPieChart {
        "borderSize": number;
        "data": {
        id: number
        percent: number
        color: string
        label?: string
    }[];
        "radius": number;
        "type": 'pie' | 'donut';
        "viewBox": number;
    }
}
declare global {
    interface HTMLMyGraphElement extends Components.MyGraph, HTMLStencilElement {
    }
    var HTMLMyGraphElement: {
        prototype: HTMLMyGraphElement;
        new (): HTMLMyGraphElement;
    };
    interface HTMLMyPieChartElement extends Components.MyPieChart, HTMLStencilElement {
    }
    var HTMLMyPieChartElement: {
        prototype: HTMLMyPieChartElement;
        new (): HTMLMyPieChartElement;
    };
    interface HTMLElementTagNameMap {
        "my-graph": HTMLMyGraphElement;
        "my-pie-chart": HTMLMyPieChartElement;
    }
}
declare namespace LocalJSX {
    interface MyGraph {
        "name"?: string;
        "points"?: Point[];
    }
    interface MyPieChart {
        "borderSize"?: number;
        "data"?: {
        id: number
        percent: number
        color: string
        label?: string
    }[];
        "radius"?: number;
        "type"?: 'pie' | 'donut';
        "viewBox"?: number;
    }
    interface IntrinsicElements {
        "my-graph": MyGraph;
        "my-pie-chart": MyPieChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-graph": LocalJSX.MyGraph & JSXBase.HTMLAttributes<HTMLMyGraphElement>;
            "my-pie-chart": LocalJSX.MyPieChart & JSXBase.HTMLAttributes<HTMLMyPieChartElement>;
        }
    }
}
