/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Point } from "./models/graph.model";
export namespace Components {
    interface MyGraph {
        "name": string;
        "points": Point[];
    }
}
declare global {
    interface HTMLMyGraphElement extends Components.MyGraph, HTMLStencilElement {
    }
    var HTMLMyGraphElement: {
        prototype: HTMLMyGraphElement;
        new (): HTMLMyGraphElement;
    };
    interface HTMLElementTagNameMap {
        "my-graph": HTMLMyGraphElement;
    }
}
declare namespace LocalJSX {
    interface MyGraph {
        "name"?: string;
        "points"?: Point[];
    }
    interface IntrinsicElements {
        "my-graph": MyGraph;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-graph": LocalJSX.MyGraph & JSXBase.HTMLAttributes<HTMLMyGraphElement>;
        }
    }
}
